#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16

pipelines:
  branches:
    develop:
      - step:
          name: Build and Test
          caches:
            - node
          script:
            - yarn install
            - yarn build-staging
          artifacts:
            - dist/*
            - dist/**/*
            - dist/**/**
      - step:
          name: Deploy
          deployment: Test
          script:
            - pipe: atlassian/sftp-deploy:0.5.7
              variables:
                  USER: $FTP_USER
                  PASSWORD: $FTP_PASSWORD
                  SERVER: $FTP_HOST
                  REMOTE_PATH: $REMOTE_FILE_PATH
                  LOCAL_PATH: 'dist/'
                  DEBUG: 'true'
                  EXTRA_ARGS: '-P 22'
            - echo "Your deployment to staging script goes here..."